trigger:
  branches:
    include:
      - main

pool:
  name: default

variables:
  acrName: nodeacrshared12345
  imageName: node-app
  imageTag: $(Build.BuildId)

stages:

# =========================
# BUILD & PUSH STAGE
# =========================
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
    - job: Build
      displayName: Build Image
      steps:

        - script: |
            echo "Checking repo structure..."
            pwd
            ls -R
          displayName: Debug Repo

        - task: Docker@2
          displayName: Login to ACR
          inputs:
            command: login
            containerRegistry: uat-service-connection

        - task: Docker@2
          displayName: Build and Push Image
          inputs:
            command: buildAndPush
            repository: $(imageName)
            dockerfile: app/Dockerfile
            buildContext: app
            containerRegistry: uat-service-connection
            tags: |
              latest
              $(imageTag)

# =========================
# DEPLOY STAGE
# =========================
- stage: Deploy
  displayName: Deploy to VM
  dependsOn: BuildAndPush
  condition: succeeded()

  jobs:
    - job: DeployToVM
      displayName: Run Container
      steps:

        - task: Docker@2
          displayName: Login to ACR
          inputs:
            command: login
            containerRegistry: uat-service-connection

        - script: |
            echo "Pulling latest image..."
            docker pull $(acrName).azurecr.io/$(imageName):latest

            echo "Stopping old container..."
            docker stop nodeapp || true
            docker rm nodeapp || true

            echo "Freeing port 3000..."
            fuser -k 3000/tcp || true

            echo "Starting new container..."
            docker run -d \
              --name nodeapp \
              -p 3000:3000 \
              --restart unless-stopped \
              $(acrName).azurecr.io/$(imageName):latest

            echo "Deployment successful!"
          displayName: Deploy Container