trigger:
  branches:
    include:
      - main

pool:
  name: milan-self-hosted

variables:
  imageName: node-app
  acrLoginServer: nodeacr12345.azurecr.io
  tag: $(Build.BuildId)

steps:

# Build and Push Docker Image to ACR
- task: Docker@2
  displayName: Build and Push to ACR
  inputs:
    command: buildAndPush
    containerRegistry: service-connection-spn
    repository: $(imageName)
    Dockerfile: app/Dockerfile
    buildContext: app
    tags: |
      $(tag)
      latest

# Stop Existing Container if Running
- script: |
    docker stop node-app-container || true
    docker rm node-app-container || true
  displayName: Stop Existing Container

# Run New Container
- script: |
    docker run -d \
      --name node-app-container \
      -p 3000:3000 \
      $(acrLoginServer)/$(imageName):latest
  displayName: Run New Container